services:
  app:
    build:
      context: . # Dockerifleがあるディレクトリのパスを定義
      dockerfile: Dockerfile # Dockerfile名を指定
    ports: # ホストとコンテナのポートを紐づける
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true # ホットリロード機能を有効化